version: '3.8'
services:
  live-streaming-mjpeg:
    build: .
    command: >
      sh -c 'gunicorn -b 0.0.0.0:5000 server:app'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
