version: '3.8'
services:
  python_server:
    build: .
    command: >
      sh -c 'python server.py'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development

    extra_hosts:
      - "host.docker.internal:host-gateway"
